DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS widgets CASCADE;
CREATE TABLE tasks (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  title VARCHAR(255) NOT NULL,
  category VARCHAR(255),
  is_done BOOLEAN DEFAULT FALSE
);

